[experiment]
project           = "EasingColorShifts.jl"
name              = "fashion_mnist"
savedir           = "output/"
rngseed           = 123
logging           = false
nogpu             = false

[data]
batchsize         = 16
tilesize          = 64

[model]
noised_channels   = 1
dropout_p         = 0.0
sigma_max         = 100.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 30
freq_chckpt       = 30

[loss]
avg_weight        = 1
dev_weight        = 1

[sampling]
nsteps            = 1000
nsamples          = 200
nimages           = 25
sampler           = "euler"
tilesize          = 64
